### ISSUE TITLE
Feature(task): Add unarchive to taund and taproj

### ISSUE THREAD

**Issue by dmyna** [dmyna/fypm#20]
## Problem
Currently, you can archive a task with `taban c` or an entire project with `taproj c`, but you cannot unarchive.

## Solution
Create an option/enum_value on `taban` to revert tasks and reuse it to unarchive an entire project in `taproj`.

**Comment by kabeer95** [comment]
i can fix it

**Comment by dmyna** [comment]
> i can fix it

Your help is much appreciated!
Do you need extra information on the issue? I can explain what I was thinking about this

**Comment by kabeer95** [comment]
kindly provide the details @dmyna

**Comment by dmyna** [comment]
> kindly provide the details @dmyna

I added the description, see if it's useful

**Comment by dmyna** [comment]
Do you know how to write Rust code and know about TaskWarrior?

**Comment by kabeer95** [comment]
Yes I know how to write rust code and I also know about the task warrior

**Comment by dmyna** [comment]
> Yes I know how to write rust code and I also know about the task warrior

Amazing, I'm counting on you! You can message me on Discord if you need help :) <3

**Comment by kabeer95** [comment]
just last thing it's a paid issue fix ? @dmyna

**Comment by dmyna** [comment]
> just last thing it's a paid issue fix ? @dmyna 

Oh, unfortunately no. This is a completely open source and non-profit project

**Comment by kabeer95** [comment]
got it
